### ISSUE TITLE
trailing commas in update.json cause JSONDecodeError

### ISSUE THREAD

**Issue by IzzySoft** [ya0211/magisk-modules-repo-util#10]
If an `update.json` has a trailing comma (like [this one](https://raw.githubusercontent.com/CrazyBytesVE/GMS-Doze/GMS-Doze/update.json)), it causes `sync` to fail, throwing a

    JSONDecodeError(Expecting property name enclosed in double quotes: line 6 column 1 (char 243))

A possible solution to this is e.g. [outlined here](https://stackoverflow.com/a/67357257/2533433): JSON5 allows trailing commas. So maybe that could be used for parsing? Quoting:

```python
>>> import json5
>>> json5.loads('{"key1": "{my special value,}",}')
{u'key1': u'{my special value,}'}
```

From a quick glance it could be a drop-in replacement.

**Comment by SanmerDev** [comment]
If only this one error, I think we don't have to import json5 yet (I will try other methods first).

**Comment by IzzySoft** [comment]
Fine with me, thanks! The linked SO Q&A has several alternative approaches as well. And I don't know what other improvements json5 might hold, or if it could cause other complications – so I leave this entirely to you.

**Comment by SanmerDev** [comment]
According to  [Magisk Developer Guides](https://topjohnwu.github.io/Magisk/guides.html#magisk-modules), there will be no comments here, just remove the trailing comma, use regular expressions to match and replace it.

**Comment by IzzySoft** [comment]
Thanks, works fine – just verified against the above "example mod". Now it would be nice if the ZIP retained its date as well (you have the timestamp in `track.json` fine as `last_update`, so maybe touch the ZIP with that?)
