### ISSUE TITLE
quoted versionCode in update.json causes ValueError

### ISSUE THREAD

**Issue by IzzySoft** [ya0211/magisk-modules-repo-util#11]
I know this is rather the fault of the module author, but maybe if `versionCode` is defined as string but `isNumeric`, it could simply be converted to `int`? Example [from here](https://github.com/Magisk-Modules-Alt-Repo/AdGuardDNS4Magisk/blob/1b04d347ff43ef10a64436a52860221b5662d80a/update.json):

```json
{
    "version": "2.7f",
    "versionCode": "27",
    "zipUrl": "https://github.com/Magisk-Modules-Alt-Repo/AdGuardDNS4Magisk/releases/download/2.7f/AdGuardDNS4Magisk-v2.7f.zip",
    "changelog": "Update to Magisk v24"
}
```

on `sync` gives

    ERROR: AdGuardDNS4Magisk: update module failed: ValueError(invalid literal for int() with base 10: '27f')

**Comment by SanmerDev** [comment]
This comes from the wrong version Code of the module. I noticed that the [module.prop](https://github.com/Magisk-Modules-Alt-Repo/AdGuardDNS4Magisk/blob/main/module.prop) in its repo has been fixed, but it is still wrong in the released [module.](https://github.com/Magisk-Modules-Alt-Repo/AdGuardDNS4Magisk)

**Comment by SanmerDev** [comment]
I plan to refactor the logging, redefine the error type and message (this should make the error clear)🧐

**Comment by IzzySoft** [comment]
Thanks for explaining plus the planned improved logging – and apologies for "spamming" you with issues; they are just proof of my intensive use and testing :wink:

**Comment by SanmerDev** [comment]
It’s OK, util still leaves a lot to be desired. I'll start working on these issues after providing [Crowdin](https://crowdin.com/) help localization for MRepo. 😋

**Comment by IzzySoft** [comment]
You sure it should be Crowdin?

![image](https://user-images.githubusercontent.com/6781438/227867685-1014c571-31d3-40f4-bd22-512e144fe742.png)

May I rather suggest using [Codeberg's Weblate](https://translate.codeberg.org/)?

![image](https://user-images.githubusercontent.com/6781438/227868307-93021df9-4e37-42ba-bdcb-1c68836c8c49.png)

**Comment by SanmerDev** [comment]
Looks good😋, I want to build one of my own [weblate](https://weblate.org).

**Comment by IzzySoft** [comment]
Codeberg is a community-driven project, especially for (and by) FOSS-projects. I work with them already since their very start: great people, great support, all FOSS. I can highly recommend them (also for project hosting; I've moved almost all of my projects from Github there. And I'd suggest using their Weblate, so you don't have the burden of maintaining your own installation and can instead focus on MRepo and repo-util :stuck_out_tongue_winking_eye:

**Comment by SanmerDev** [comment]
> Codeberg is a community-driven project, especially for (and by) FOSS-projects. I work with them already since their very start: great people, great support, all FOSS. I can highly recommend them (also for project hosting; I've moved almost all of my projects from Github there. And I'd suggest using their Weblate, so you don't have the burden of maintaining your own installation and can instead focus on MRepo and repo-util 😜

Good job🥳, but I'm going to build it by myself, while I still have enough energy to touch more things I haven't done.😋

**Comment by SanmerDev** [comment]
Give up🫠, Weblate wants a high performance server. 🤪

**Comment by IzzySoft** [comment]
So Codeberg then?

**Comment by SanmerDev** [comment]
> So Codeberg then?

In progress 🥳

**Comment by SanmerDev** [comment]
@IzzySoft I have a question🤔, how to update the avatar of translation service, it seems to be different from codeberg.org🤨

**Comment by IzzySoft** [comment]
No idea, I've never played with that, sorry. Codeberg has an IRC channel (`#codeberg` at Libera Chat), maybe you could ask there?
