### ISSUE TITLE
Questions on updating modules

### ISSUE THREAD

**Issue by IzzySoft** [ya0211/magisk-modules-repo-util#15]
When using an `update.json` provided by the module's own repo, things are clear: I point `update_to` to that, and updates are handled upstream. But when upstream does not provide an `update.json`, what options do I have to handle updates?

### local `update.json`
This is not supported by repo-util as it requires the address to start with `http` (`isWith('http','json')`). Would be great if a local `update.json` could be supported; while the name is already reserved in this space, one could use e.g. `upstream.json` (or any other name as long as it ends with `.json`) which would be looked for in the module's folder then. What do you think?

### from URL
This is [described here](https://github.com/ya0211/magisk-modules-repo-util#upload-from-url). What is not 100% clear is how that deals with multiple versions. Say I initially set `update_to` to `.../version_v1.0.zip`, that would be added to our Magisk.repo. Now v1.1 is released, and I update the URL in `update_to` to point to `.../version_v1.1.zip`. What would happen on the next sync? Would the existing `version_v1.0.zip` be *replaced* – or would the new ZIP be added (until `max_num` is reached, which then would purge the oldest ZIP)? I assume the latter, but just want to make sure.

### upload from local
As I understand [the description](https://github.com/ya0211/magisk-modules-repo-util#upload-from-local), I'd need to have a directory `local/` at the same level where `modules`, `json/` etc are located (maybe you add that in the [for developer](https://github.com/ya0211/magisk-modules-repo-util#for-developer) section?). There I'd place the ZIP file, then specify it with `update_to`. Will the ZIP then be duplicated to the `modules/<id>` directory? Or will it be moved there? If I update to the next version, will both ZIPs have to stay in `local/`?

### from .git
Here I assume it's a set-and-forget like with `update.json`. Out of curiosity, what would be needed for that to work? How does it pull updates? What's needed in the referenced git repo for it to work? I guess it's using upstream's `module.prop` then; but ho does it identify the matching ZIP? Is it building the module itself?

Thanks in advance for your explanations, @ya0211!

**Comment by SanmerDev** [comment]
### from local update.json
If so, `update.json` is controlled by the repo owner, then every version update has to edit `update.json`, how is this different from `from url`


### from url
This option is for those have the same url to release new modules, if url has changed, you have to edit it


### from git
This option is for those you can get the module by packaging all files in the repository (such as [Magisk-Modules-Alt-Repo](https://github.com/Magisk-Modules-Alt-Repo), [Magisk-Modules-Repo](https://github.com/Magisk-Modules-Repo))


No matter which way there is always a version detection mechanism, `update.json` will not be edited under the same version, but the zip will be downloaded and refreshed, which needs to be improved(#6)

**Comment by IzzySoft** [comment]
* **how is this different from `from url`:** the latter specifies a ZIP. So how do I update that `update_to` later? OK, I can modify the corresponding `track.json` directly instead of modifying yet another copy (`upstream.json`). So the idea was rather to not fiddle with the files of repo-util directly, as structures might change.
* **from url:** Now I understand that. Thanks for adding that phrase to the corresponding block in the Readme! Much clearer now :smiley: Maybe you also use an example URL matching that description? `releases/download/v1.8.6/LSPosed-v1.8.6-6712-zygisk-release.zip` looks rather version-specific, which implies the URL needs to be updated for each new release (that's what initially confused me).
* **from git:** that I learned tonight by creating a test repo to play with (see my bug report and PR), thanks!

What I still do not understand completely is **from local**. Will the files remain in `local/` after `config -a` has added them to `modules/`? Sure I could "just try and see", but it certainly would be much better if the description were clear, so not everybody as to "just try and find out" :wink:

Thanks a lot! Repo is growing. Running in "open beta" mode now for about a week, feedback so far was positive :smiley:

**Comment by SanmerDev** [comment]
- `from local update.json`: in order not to modify `track.json` frequently, I will add support for this
- `from local`: in order to ensure the integrity of the repo, the files will be copied to modules/{id}
- `from git`: that issue has been fixed, you can try it

I think it's still a while before the stable release, I still need some time to deal with these issues 🤪.

**Comment by IzzySoft** [comment]
Thanks! Confirming 1 and, from what I could see so far, 3 (didn't know creating the module was as easy as zipping up the repo content. Especially as some repos seem to have the module itself in some sub-directory: would `from git` still work fine with that? Even if the repo is shared by an app and a module? I've seen some where I didn't even know where to look at).

As for `from local`: so the repo owner then has to take care for cleanup manually? And files from multiple different modules can co-exist there (provided even their changelogs have different file names)?

> I think it's still a while before the stable release

well, I didn't exactly minimize the backlog, did I? :see_no_evil:

**Comment by SanmerDev** [comment]
> Especially as some repos seem to have the module itself in some sub-directory

Need an example, I'll check if I can adapt

> And files from multiple different modules can co-exist there

You can solve this issue by using the same file name, I'm working on #6, for modules from local, the timestamp is last edited. 
Of course, if you want to keep different versions, you can use different files, but need edit `track.json`. Actually once it's copied, it's useless, but I didn't clean it up (it will still be needed if something goes wrong)

**Comment by IzzySoft** [comment]
> Need an example, I'll check if I can adapt

will keep my eyes open and name it when found, thanks! Wait, what for did I bookmark **my** backlog:

* [MagiskHide](https://github.com/HuskyDG/MagiskHide): compare the repo content to the ZIP attached to releases. That one is not just "zipping up the tree", it involves building the libraries from source (`build.sh`) it seems.
* [Pixelify](https://github.com/Kingsman44/Pixelify): no module ZIP to compare against, but simply zipping up the tree certainly wouldn't do the trick here either. It's most likely zipping up the `module/` sub-tree, but I'm not sure.
* [acc](https://github.com/VR-25/acc): comes as multiple ZIPs (installer, uninstaller) and bundles things via a `module.json` it seems. I wouldn't have deduced that from the `module.prop` if there were no files attached to releases.
* [backtap](https://github.com/xarantolus/backtap): most files are inside `module/backtap/`, but not the `system/` folder. Which cannot be found anywhere in the source tree; the contained ELF binary is most likely build from source (`build.gradle` in the root directory)
* [dfps](https://github.com/yc9559/dfps): the entire module seems to be built from source (`build.sh`)

Guess that should be enough for starters :wink: Feel free to move that to a separate issue if that helps tackling one thing at a time. As for now, one should be careful what modules can be built by simply zipping up the tree. As a repo maintainer, I would need to test them all first myself to be sure what I can ship – but how realistic is that? Are there any recommendable safe-guards?

> Actually once it's copied, it's useless, but I didn't clean it up (it will still be needed if something goes wrong)

OK, maybe mark it "experimental" for now in the Readme? Like, "use this method at your own risk for now" (which might be applyable to `from git` as well, seeing above examples :see_no_evil:)

I saw you also added `from local JSON` to the Readme already, great! So I could have a bunch of `<module_id>.json` in `local/` to use that, right? That, with the original `from JSON` (which is the only one I've used up to now), and `from git` working well, I guess I'm covered very well to handle different sources, thanks! With `from git` I'll stick to the "simple cases" for now, until I've named you a few more complex one and you confirmed. Basically, I didn't know before that creating a module from its git repo would be as simple as zipping up the content :see_no_evil:

**Comment by SanmerDev** [comment]
For the modules that need to be built, you cannot use from git to add them, there is no solution to this but to replace it in other ways.

Unfortunately, there is no way to provide safe-guards now, it may have to wait until the repo-util is stable, because it is still iterating rapidly. You can copy a repo for testing 🤪.

**Comment by IzzySoft** [comment]
> Actually once it's copied, it's useless, but I didn't clean it up (it will still be needed if something goes wrong)

Yeah, and when I remove it manually, this is what happens:

```
Sync ERROR: unlimited-hotspot: update module failed: FileNotFoundError(No such file: 'magisk/local/v5_5.zip')
```

and the module disappears from `modules.json`. Since today's update at least, before that it was retained (with `update_to` being empty even – doesn't work now either. Keeping the broken URL in causes the entire webpage being dumped; looks like the case that a link to an `update.json` returning a 404 HTML error is not covered :wink:). Files are still there in `modules/unlimited-hotspot/`. As long as all files are available in `modules/`, they should also be listed in `modules.json`. Could you please adjust that? Must have been something you changed today, before that I got, as expected, `will be keep because available versions exists` (which btw should say `will be kept` or `will keep` :wink:)

It's happening in `Repo.py`, inside `def pull`. The condition for keeping the module changed from

    if local_update_json.exists() and old_module is not None:

to

    if self._check_latest_version(module):

(where an update check is performed; maybe when that fails, as it does here…?) Funny thing is that if I replace that condition with `if True:`, it works fine – except that the name of the module is no longer set… because `modules.json` then only has

```json
    {
      "id": "unlimited-hotspot",
      "license": "WTFPL"
    },
```

For the moment I mitigated that by keeping a copy in `local/` and placing that file name into `update_to`. And now we both know what it is that "goes wrong" when removing that :see_no_evil: Basically: that file is used to retrieve the `module.prop` from. Which in this case should rather be taken from the existing record (or the ZIP in `modules/`, as the `name` attribute is only available in the ZIP file's `module.prop`, not in `track.json` or `update.json`, where it would save us from unzipping on each run).

> For the modules that need to be built, you cannot use from git to add them, there is no solution to this but to replace it in other ways.

Thought so – thanks for confirming! In hind-sight I now also understand the comment in the Readme. Maybe include a warning like "You cannot use this method when creating the module involves steps other than simply zipping the contents, e.g. running build scripts."

> Unfortunately, there is no way to provide safe-guards now, it may have to wait until the repo-util is stable, because it is still iterating rapidly.

Understood. Just thought you might have had some ideas. The simple existence of files like `build.sh` or `build.gradle` are rather indicators than proof.

**Comment by SanmerDev** [comment]
> the module disappears from modules.json

If update failed, it will check `update.json` for available version, this will only happen if update fails and no available version exists.

**Comment by IzzySoft** [comment]
Now that's funny. I just try to reproduce it step-by-step to track down the culprit, and now it works as expected? :zany_face: Strange. No idea what that was then. I'll keep an eye on it but consider it a "fluke" for now (which hopefully does not repeat). Apologies for the "false alert" then!

Guess that means this issue is solved now (unless there are some points you wish to track), so close? Thanks a lot again for your help! I also love to see the `added` property having been, uh, added to `track.json` already :smiley:

**Comment by SanmerDev** [comment]
> If update failed, it will check update.json for available version, this will only happen if update fails and no available version exists

That's how it's designed (for all `update ways`), but if there's a issue, you can raise it.

Direct feedback is ok, if there is a issue in a `update way` (providing an example is best), I will track the issue by myself.

**Comment by IzzySoft** [comment]
You might be interested in my mechanism for "updating the local `update.json`", as I can imagine it to be implemented directly in repo-util :wink:

```json
{
    "version": "0.1.0",
    "versionCode": 1,
    "moduleProp": "https://github.com/galeksandrp/app-data-file-exec/raw/master/module.prop",
    "urlPattern": "https://github.com/galeksandrp/app-data-file-exec/releases/download/v%v/app-data-file-exec-%v.zip",
    "zipUrl": "https://github.com/galeksandrp/app-data-file-exec/releases/download/v0.1.0/app-data-file-exec-0.1.0.zip",
    "changelog": ""
}
```

`version` and `versionCode` are clear. `moduleProp` is an URL to the (raw) `module.prop` file ustream, where my update checker takes the (upstream `version` and `versionCode` from – what you are probably doing for `from git` as well. It also takes the `id` to make sure it matches the configured module. Next it compares the two `versionCode`s. If an update is detected, it uses `urlPattern` to update the `zipUrl`, by replacing each occurrence of `%v` with the content of upstream's `version`, and `%c` by upstream's `versionCode`.

Basically this is a mix of `from git` and `from JSON`. Works fine here (as long as a proper match can be made; it won't work with e.g. a `version=v0.1.0` if the URL instead has `download/V1.0/` – in other words, the only "changing parts" of `zipUrl` must be those that can be filled by `version` and/or `versionCode`. Usually that does fit, so such local JSON can substitute a missing "remote JSON".

If you'd wish to implement that, the best way would probably be doing so in `track.json` – and applying this "update pattern" whenever both, `moduleProp` **and** `urlPattern` are present and non-empty. And again, just if you find it useful – I have that implemented here with "local JSON" and it works fine for me, so I have no "urgent need" to have it implemented in repo-util (though it then would save me running extra code :see_no_evil:). Just let me know should it be implemented :smile:

**Comment by IzzySoft** [comment]
Woah, now comes the load of commits :see_no_evil: You've been quite busy on all that! Will you let me know what I need to adjust on my end for each of the closed issues?

**Comment by SanmerDev** [comment]
@IzzySoft The repository structure remains unchanged, but `sync` package has been modularized and decoupled. For users, this is simply an improvement to `cli.py`. As for the improvement of cli.py, you can check it yourself.

**Comment by IzzySoft** [comment]
> The repository structure remains unchanged

Thanks! That was my main concern indeed, how "upgrading" from an existing (older) repository structure would work. It were simply too many commits to check them all :see_no_evil:

> As for the improvement of cli.py, you can check it yourself.

Guess I will have to – especially to see where "old syntax" is no longer available, and I'd have to adjust my scripts here accordingly. As recommended by you earlier, I will still wait with updating until you say it's safe and name the commit/tag to use :wink: Thanks a lot for all your hard work on this!

**Comment by SanmerDev** [comment]
I just did a simple test, all functions are available, but there may be omissions (you can try). 

When it's ready, I'll release the first version. then, I will start to refactor the repository structure, two issues will be finished, and more properties will be added for the new version of MRepo.

**Comment by IzzySoft** [comment]
Thanks!
