### ISSUE TITLE
Bug with updating from GIT

### ISSUE THREAD

**Issue by IzzySoft** [ya0211/magisk-modules-repo-util#16]
I've just tried to obtain a module via its git URL. The resulting ZIP does not match the one provided by upstream; it seems some directory-separator is missing:

![image](https://user-images.githubusercontent.com/6781438/229388445-c462d908-41ae-4499-91e8-f7652a8b0706.png) ![image](https://user-images.githubusercontent.com/6781438/229388469-7035cdfd-8a5e-4578-88d5-e6d375511a43.png)

The left screenshot shows the structure of the ZIP as provided by the module's author. The right one is what repo-util created. Note the files:

* `commonfunctions.sh` in the original module is `common/functions.sh`
* `systemplaceholder` originally is `system/placeholder`

No files are missing. Is there some bug with `_get_module_from_git`? Or rather with `git_clone`?

```python
    with ZipFile(out, "w", ZIP_DEFLATED) as f:
        for dir_path, dir_names, file_names in os.walk(repo_dir):
            file_path = dir_path.replace(repo_dir.as_posix(), "")
            for file_name in file_names:
                f.write(os.path.join(dir_path, file_name), file_path + file_name)
```

The last line looks wrong. Shouldn't that be

```python
               f.write(os.path.join(dir_path, file_name), os.path.join(file_path,file_name))
```

Adjusting it that way makes the archive looking fine. Further, the two lines before above block:

```python
    shutil.rmtree(repo_dir.joinpath(".git"), ignore_errors=True)
    shutil.rmtree(repo_dir.joinpath(".github"), ignore_errors=True)
```

miss some more removals: `.gitlab` tree, and files like `.gitattributes` and `.gitignore`.

**Comment by SanmerDev** [comment]
It's strange that in the repo I built 🤔, the zip file didn't have this error, but this will be fixed by the new packaging method.

**Comment by IzzySoft** [comment]
Haha, no, the error only comes up with sub-directories being used in the repo. Maybe the one you used didn't have such. But then, all of them have the `META-INF/` directory – which funnily was packed properly :thinking: Well, it works now :smiley: Thanks!

**Comment by SanmerDev** [comment]
No, the [mirror](https://github.com/ya0211/magisk-modules-alt-repo)  of magisk-modules-alt-repo also has this issue🤪, but no one reported it😂

**Comment by IzzySoft** [comment]
Are you keeping that mirror up-to-date – or should one rather add the original one, if one wanted to use the Alt Repo?
