### ISSUE TITLE
Some modules are updated on each scan despite not having been changed

### ISSUE THREAD

**Issue by IzzySoft** [ya0211/magisk-modules-repo-util#18]
Some modules are updated on each scan despite not having been changed for many month, and I have no idea why. Here are 2 examples using remove `update.json`:

* https://github.com/CrazyBytesVE/QS-Modded (last updated 8 months (!) ago)
* https://github.com/Jefferderp/Magisk-KeyboardRemaps (last updated 3 months ago)

Both still have `versionCode=1`. For both, the `last_update` stays the same after the ZIP has been fetched again. But for both the timestamps of the files inside `modules/` are touched on each run, and the log indicates they have been updated.

**Comment by SanmerDev** [comment]
`versionCode=1` in *module.prop*, but `versionCode=10` in *update.json*, so these two modules are always judged as having the latest available 🤨.

This is the developer's responsibility 🙃.

**Comment by IzzySoft** [comment]
Ah, that was the piece I've missed! Thanks! Reported upstream and (meanwhile) fixed locally (updated versionCode in the local `update.json` and `module.prop`). :smile:
