### ISSUE TITLE
field names in modules.json

### ISSUE THREAD

**Issue by IzzySoft** [ya0211/magisk-modules-repo-util#20]
I've never checked before but always thought you'd just extended the format used by the "official repos". But comparing the [`modules.json` of the Magisk-Alt-Repo](https://github.com/Magisk-Modules-Alt-Repo/json/blob/main/modules.json) with mine, I see the fields are named entirely different. This is what the Alt-Repo's looks like:

```json
{
    "last_update": 1598596016000,
    "modules": [
        {
            "id": "acc",
            "last_update": 1680282963000,
            "notes_url": "https://raw.githubusercontent.com/Magisk-Modules-Alt-Repo/acc/master/README.md",
            "prop_url": "https://raw.githubusercontent.com/Magisk-Modules-Alt-Repo/acc/master/module.prop",
            "stars": 7,
            "zip_url": "https://github.com/Magisk-Modules-Alt-Repo/acc/archive/master.zip"
        },
```

and this is from mine:

```json
{
  "name": "IzzyOnDroid Magisk Repo",
  "timestamp": 1681150305.993857,
  "modules": [
    {
      "id": "AOSPMods",
      "license": "GPL-3.0-only",
      "version": "2.7.2",
      "versionCode": 233,
      "name": "AOSP Mods (Xposed version)",
      "author": "Siavash79 + ElTifo",
      "description": "Xposed based module for customizations on SystemUI on AOSP based roms. Supports Android 12+",
      "states": {
        "zipUrl": "https://apt.izzysoft.de/magisk/modules/AOSPMods/2.7.2_233.zip",
        "changelog": "https://apt.izzysoft.de/magisk/modules/AOSPMods/2.7.2_233.md"
      }
    },
```

Now trying to add your or mine to a client like FoxMMM won't work, as the only matching field name is the module's `id`. If the fields that are matching would be named alike, other clients (hopefully) would simply ignore the additional ones. What do you think?

(I just stumbled on this as some folks asked me why they couldn't add my repo to FoxMMM. Which also raised the question if they could e.g. add the Alt-Repo to MRepo directly, or only via your mirror?)

**Comment by SanmerDev** [comment]
Since there never was an `official json format`, I uses a scheme which I like, I don't think [modules.json of the Magisk-Alt-Repo](https://github.com/Magisk-Modules-Alt-Repo/json/blob/main/modules.json) is a good choice, the zip they use is not a real magisk module.

**Comment by IzzySoft** [comment]
OK, thanks! So you think even if we made the format of the JSON "compatible", it won't work anyway (as we'd ship a "real module" in the ZIP)?

**Comment by SanmerDev** [comment]
It shouldn't be up to repositories to adapt clients, this should be done by clients.

**Comment by IzzySoft** [comment]
Yes, full ack to that. I just try to evaluate possibilities. Looking from the users' perspective, this is technically correct – but if the client maintainer cannot "quickly implement" it – and MRepo lacks some functionality they need which "the other" has… I could e.g. have my magisk-repo class export a `modules.json` in the format used by other clients, to mitigate for a while. But yes, that could lead to either not working anyway (different ZIP than expected) – or to the maintainers of those other clients to see no urgency :man_shrugging:

That said, it would be nice to have a (base) standard to agree upon. But if that's not possible, we'll have to accept that. I lack the deep insight to tell or argue here, so I'll accept your decision :smile:
