### ISSUE TITLE
Problem with ghproxy in zipUrl

### ISSUE THREAD

**Issue by IzzySoft** [ya0211/magisk-modules-repo-util#35]
I've noticed this already for a while:

    Pull ERROR: from_json: [Hc_memory] -> ConnectionError(HTTPSConnectionPool(host='ghproxy.com', port=443): Max retries exceeded with url: /https://github.com/OneB1ank/A1Memory/releases/download/Richard8/A1Memory-2023-11-26.zip (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f558fbf2430>: Failed to establish a new connection: [Errno 110] Connection timed out')))

Here's the corresponding `track.json`:

```json
{
  "id": "Hc_memory",
  "enable": true,
  "update_to": "https://github.com/OneB1ank/A1Memory/raw/main/version.json",
  "license": "GPL-3.0-only",
  "source": "https://github.com/OneB1ank/A1Memory",
  "support": "https://github.com/OneB1ank/A1Memory/issues",
  "added": 1688711365.002626,
  "last_update": 1699429588.0,
  "versions": 3
}
```

The problem lies in that project's `update.json` (called `version.json` there):

```json
{
	"version": "v4 (2023.11.26)",
	"versionCode": 439,
	"zipUrl": "https://ghproxy.com/https://github.com/OneB1ank/A1Memory/releases/download/Richard8/A1Memory-2023-11-26.zip",
	"changelog": "https://ghproxy.com/https://raw.githubusercontent.com/OneB1ank/A1Memory/main/changelog.md"
}
```

Maybe repo-util could simply `s!https://ghproxy.com/https:!https:!` on the zipUrl (as there might be other proxies, though I haven't encountered any yet: I basically mean "extracting the real URL")? Currently, according to the logs it somehow adds a "leading slash" to the full URL, which then of course does not work.

**Comment by SanmerDev** [comment]
This should be a limitation of ghproxy.com. Requests will be rejected after too many requests.

**Comment by IzzySoft** [comment]
Could be, but it happens **each time** that specific module gets updated. And AFAIR this is the only module in my repo using ghproxy (I cannot perform a "quick check" as that specification is part of the `update.json` in the corresponding modules' repositories).

Unfortunately, I cannot modify the `version.json` file before running `cli.py` as it is "remotely hosted", so adjusting the URL is not what I can do. Hence the question if you see a possibility repo-util could handle that, e.g. by (optionally?) stripping the proxy (I have no idea why someone puts in a proxy there in the first place – I'd say GH can handle that fine itself). For the past updates, I've performed the update manually (downloading ZIP and changelog, naming them accordingly, manually adding the corresponding section to `update.json`), but I'd prefer it working automatically.

If you say that's not for repo-util to deal with, I'll of course try reaching out to the module developers instead. I brought it here first as it might affect other modules (which are not in my repo (yet)) as well, so a "general solution" could be established.

What irritates me is the "leading slash" in the log. Does repo-util really try connecting to "/https…" – or is that just the "path" it requests from ghproxy? I guess it's the latter, but it just looks quite strange :see_no_evil:

**Comment by SanmerDev** [comment]
It works correctly after I try it (but it fails a few times).

I think this is more down to network issues, and this is a rare occurrence so I won't be fixing it.

**Comment by IzzySoft** [comment]
OK, might be the same thing as back then with "pull" (what I commented on yesterday in the other issue: that problem existed for a few weeks, and then suddenly disappeared without me having updated repo-util even). So yeah, up to you. I just wanted to bring it to your attention so you know there "is something". Feel free to close then, or to leave it open a little longer to see if someone else chimes in – or the problem gets bigger, or whatever :wink:
