### ISSUE TITLE
[Submit] Submitting a module

### ISSUE THREAD

**Issue by zgfg** [ya0211/magisk-modules-repo-util#4]
Hello

I have installed your (beta) MRepo app and seen your new Repo for Magisk modules

I'd like to test and to submit my module ToyBox-Ext

Hopefully, the config.json and hosts.json are filled correctly:

config.json:
{
  "repo_name": "ToyBox-Ext",
  "repo_url": "https://github.com/zgfg/ToyBox-Ext/",
  "repo_branch": "main",
  "sync_mode": "git",
  "max_num_module": "",
  "show_log": "",
  "log_dir": ""
}

hosts.json:
[
  {
    "id": "ToyBox-Ext",
    "update_to": "https://raw.githubusercontent.com/zgfg/ToyBox-Ext/main/update.json",
    "license": "OBSD",
    "changelog": ""
  }
]

**Comment by SanmerDev** [comment]
This is not necessary, I am now making MRepo support existing repo, such as [Magisk-Modules-Alt-Repo](https://github.com/Magisk-Modules-Alt-Repo), I noticed that `ToyBox-Ext` is already included in it.  

Another MRepo is dedicated to `own repository`(developers or users), I think this will be subscription-based, if you like this developer or user's repo, add it, MRepo will not force a built-in repo .

**Comment by zgfg** [comment]
Yeah, in the meantime I played myself:

Open MRepo, go to Settings, Repository and press +

Add Repo with the following URL (your mirror):
https://raw.githubusercontent.com/ya0211/magisk-modules-alt-repo/main/

Add (and I think I needed to restart the MRepo app?!)

Then, under Modules, Cloud, it displays (and let them manage) all 70 modules from Magisk-Modules-Alt-Repo

**Comment by zgfg** [comment]
![Screenshot_2023-02-21-16-39-50-516_com sanmer mrepo-edit](https://user-images.githubusercontent.com/51943147/220397117-2bc05e69-4183-42d7-8337-5c99350cf2aa.jpg)
![Screenshot_2023-02-21-16-42-04-258_com sanmer mrepo-edit](https://user-images.githubusercontent.com/51943147/220397183-f7b44d48-ecd1-4436-a64b-ccd1fb4178c7.jpg)

**Comment by SanmerDev** [comment]
> Yeah, in the meantime I played myself:
> 
> Open MRepo, go to Settings, Repository and press +
> 
> Add Repo with the following URL (your mirror): https://raw.githubusercontent.com/ya0211/magisk-modules-alt-repo/main/
> 
> Add (and I think I needed to restart the MRepo app?!)
> 
> Then, under Modules, Cloud, it displays (and let them manage) all 70 modules from Magisk-Modules-Alt-Repo

The current version of the app adding the repository doesn't refresh the data (only the button on the toolbar does it), I've noticed this and have been refactoring.
