### ISSUE TITLE
do not touch unchanged files on 'cli.py sync'

### ISSUE THREAD

**Issue by IzzySoft** [ya0211/magisk-modules-repo-util#6]
When running `cli.py sync`, despite of the log output stating for each module `already the latest version`, `update.json`, Readme and ZIP of each module are touched/changed – and thus transferred again to the remote server when running `rsync`. If a module is already up-to-date, those files IMHO should **NOT** be touched/modified. Not only does that cause unnecessary network traffic (on syncing to the server later), it also makes it harder to spot what time a module has been really last updated (especially the timestamp of the ZIP) when looking at it in the file system.

That would probably be [this line](https://github.com/ya0211/magisk-modules-repo-util/blob/main/sync/Repo.py#L275):

```python
if versions_item.versionCode <= latest_version.versionCode:
```

As this is inside `if local_update_json.exists()`, shouldn't that rather be `if versions_item.versionCode < latest_version.versionCode:` (instead of `<=`)?

**Comment by SanmerDev** [comment]
## Can be done

### non-updatable
| From | Network Traffic (Download) | Timestamp of ZIP |
|:-:|:-:|:-:|
| updateJson | update.json | no touch |
| local | None | no touch |
| others | ZIP | no touch |

### updatable
| From | Network Traffic (Download) | Timestamp of ZIP |
|:-:|:-:|:-:|
| updateJson | update.json, ZIP, changelog.md | touch |
| local | None | touch |
| others | ZIP, (changelog.md) | touch |

**Comment by IzzySoft** [comment]
Don't forget that the `*.md` and `update.json` themselves shouldn't be touched either when unchanged. Does the `timestamp` in `update.json` refer to the last check, or to the last update? In the latter case the file should only be changed if an update was pulled.

**Comment by SanmerDev** [comment]
The timestamp in update.json is the last update

**Comment by IzzySoft** [comment]
Meaning the timestamp of when the last version of the module was released – or the last time it was checked for? To me it seems they all point to the time I ran the last `cli.py sync`. For example, [Systemless Debbloater](https://github.com/zgfg/SystemlessDebloater) was last released 3 weeks ago. All timestamps here point back to yesterday 4:20 pm (which might be when I've added it here locally, but in no way reflects the release date itself). Even the directories themselves all show the time of when `cli.py sync` was last run. Which makes it really hard to check which module was last updated, or which was not updated for months.

Also, from the view of a user I'd be much more interested in when the module itself was last released than at what time it entered the repo (though the latter is also interesting if looking for "what's new", so we might need both dates).

**Comment by SanmerDev** [comment]
From `update.josn` I can't get when the current version of the module is released, Only modules added by [Upload from git](https://github.com/ya0211/magisk-modules-repo-util#upload-from-git) can sync these two timestamps.🤪

**Comment by SanmerDev** [comment]
The timestamp of the last update only means that cli.py updated this module. It is difficult for us to get the timestamp when the developer releases a new version.🤔

**Comment by IzzySoft** [comment]
> I can't get when the current version of the module is released

Ever tried looking for the LAST_MODIFIED header in the http request?

```bash
wget --method=HEAD --server-response https://github.com/zgfg/SystemlessDebloater/releases/download/151/SystemlessDebloater_v1.5.1.zip | grep Modified
  Last-Modified: Tue, 28 Feb 2023 20:16:18 GMT
```

Note that this field does not always exist, and some servers just set it to the "last cached" date or something. But it's still better than using `now()`.

**Comment by SanmerDev** [comment]
### timestamp
| From | Timestamp |
|:-:|:-:|
| (local) updateJson | Last-Modified in header |
| url | Last-Modified in header |
| git | git log |
| local | last file change |

**Comment by IzzySoft** [comment]
Yupp, that looks fine, thanks!
